---
name: ci_checks

on:

  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  GO_VERSION: '1.21'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code_changed:
    name: code_changed
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      any_modified: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.3.0
        with:
          files: |
            **/*.go
            **/*.sh
            **/Makefile
            **/Dockerfile
            **/go.mod
            **/go.sum

  codeql_analysis:
    name: codeql_analysis
    runs-on: ubuntu-latest
    needs: code_changed
    if: |
      always() && !cancelled() &&
      (needs.code_changed.result == 'skipped' || needs.code_changed.outputs.any_modified == 'true')
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'go'
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  dont_break_connectopus:
    name: dont_break_connectopus
    runs-on: ubuntu-latest
    needs: code_changed
    if: |
      always() && !cancelled() &&
      (needs.code_changed.result == 'skipped' || needs.code_changed.outputs.any_modified == 'true')
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout Connectopus
      uses: actions/checkout@v4
      with:
        repository: 'ghjm/connectopus'
        path: './connectopus'
        fetch-depth: 0

    - name: Use local golib
      working-directory: './connectopus'
      run: 'echo "replace github.com/ghjm/golib => $GITHUB_WORKSPACE" >> go.mod'

    - name: Build Connectopus
      working-directory: './connectopus'
      run: 'make'

    - name: Test Connectopus
      working-directory: './connectopus'
      run: 'make test'

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    needs: code_changed
    if: |
      always() && !cancelled() &&
      (needs.code_changed.result == 'skipped' || needs.code_changed.outputs.any_modified == 'true')
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Go linters
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        skip-cache: true

  go_tests:
    name: go_tests
    if: |
      always() && !cancelled() &&
      (needs.code_changed.result == 'skipped' || needs.code_changed.outputs.any_modified == 'true')
    needs: code_changed
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go build dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Run tests
        run: go test ./... -count=1 -race

